trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Set the Docker registry service connection
  DOCKER_REGISTRY_SERVICE_CONNECTION: 'Dockerconnectionname'
  # Image name
  IMAGE_NAME: 'flask-app'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          

         
            - task: Docker@2
              inputs:
                containerRegistry: 'sandeepconnection-new'
                repository: 'sandeep1208/sandeepapp'
                command: 'buildAndPush'
                Dockerfile: '**/Dockerfile'
              